// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCategory(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddCategory'](arg1, arg2, arg3);
}

export function AddURL(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddURL'](arg1, arg2, arg3, arg4, arg5);
}

export function AdvancedSearchURLs(arg1) {
  return window['go']['main']['App']['AdvancedSearchURLs'](arg1);
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function DeleteURL(arg1) {
  return window['go']['main']['App']['DeleteURL'](arg1);
}

export function DownloadAndApplyUpdate(arg1) {
  return window['go']['main']['App']['DownloadAndApplyUpdate'](arg1);
}

export function EnsureDataDir() {
  return window['go']['main']['App']['EnsureDataDir']();
}

export function ExportBookmarks() {
  return window['go']['main']['App']['ExportBookmarks']();
}

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetCurrentVersion() {
  return window['go']['main']['App']['GetCurrentVersion']();
}

export function GetDataDir() {
  return window['go']['main']['App']['GetDataDir']();
}

export function GetURLs() {
  return window['go']['main']['App']['GetURLs']();
}

export function GetUpdateProgress() {
  return window['go']['main']['App']['GetUpdateProgress']();
}

export function GetVersionInfo() {
  return window['go']['main']['App']['GetVersionInfo']();
}

export function ImportChromeBookmarks(arg1) {
  return window['go']['main']['App']['ImportChromeBookmarks'](arg1);
}

export function ImportNetscapeBookmarks(arg1) {
  return window['go']['main']['App']['ImportNetscapeBookmarks'](arg1);
}

export function ReorderURLs(arg1) {
  return window['go']['main']['App']['ReorderURLs'](arg1);
}

export function RestartApplication() {
  return window['go']['main']['App']['RestartApplication']();
}

export function SaveCategories(arg1) {
  return window['go']['main']['App']['SaveCategories'](arg1);
}

export function SaveURLs(arg1) {
  return window['go']['main']['App']['SaveURLs'](arg1);
}

export function SearchURLs(arg1) {
  return window['go']['main']['App']['SearchURLs'](arg1);
}

export function TestNoUpdate() {
  return window['go']['main']['App']['TestNoUpdate']();
}

export function TestUpdateAvailable() {
  return window['go']['main']['App']['TestUpdateAvailable']();
}

export function UpdateURL(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateURL'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateVersionConfig(arg1, arg2) {
  return window['go']['main']['App']['UpdateVersionConfig'](arg1, arg2);
}
