// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddCategory(arg1:string,arg2:string,arg3:string):Promise<main.Category>;

export function AddURL(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>):Promise<main.URLItem>;

export function AdvancedSearchURLs(arg1:main.AdvancedSearchOptions):Promise<Array<main.URLItem>>;

export function CheckForUpdates():Promise<main.UpdateInfo>;

export function DeleteURL(arg1:string):Promise<void>;

export function DownloadAndApplyUpdate(arg1:string):Promise<void>;

export function EnsureDataDir():Promise<void>;

export function ExportBookmarks():Promise<string>;

export function GetCategories():Promise<Array<main.Category>>;

export function GetCurrentVersion():Promise<string>;

export function GetDataDir():Promise<string>;

export function GetURLs():Promise<Array<main.URLItem>>;

export function ImportChromeBookmarks(arg1:string):Promise<number>;

export function ImportNetscapeBookmarks(arg1:string):Promise<number>;

export function ReorderURLs(arg1:Array<string>):Promise<void>;

export function SaveCategories(arg1:Array<main.Category>):Promise<void>;

export function SaveURLs(arg1:Array<main.URLItem>):Promise<void>;

export function SearchURLs(arg1:string):Promise<Array<main.URLItem>>;

export function TestNoUpdate():Promise<main.UpdateInfo>;

export function TestUpdateAvailable():Promise<main.UpdateInfo>;

export function UpdateURL(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:Array<string>):Promise<main.URLItem>;
